### ISSUE TITLE
enhancement request: release the raw source 

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-js-api#1]
very cool project!  we'd be **ecstatic** if y'all considered releasing the *unminified* source next :smile:

**Comment by ngoldman** [comment]
+1

it's not really open source if the code is obfuscated :grin:

**Comment by DavidSpriggs** [comment]
+1

This has been a long time coming! Thank you for taking this small step! We can now do builds with a lot more simplicity!

One thought about un-obfuscating this repo. I know in the past Esri has not wanted to release the source due to a fear of fragmentation. Then having to support fragmented api deployments. There is a simple remedy for this, simply tell Esri support to only support apps that use the CDN or JSO deployments.

Under this model if a developer is using a custom build or deployment (created outside the JSO) and has an issue with the api, they will need to reproduce the issue with a sample that is using the CDN. Seems simple enough.

@odoe What other concerns for full source release do you run into from the team? Let's use this as a place to discuss these issues and how to resolve them.

**Comment by nixta** [comment]
+1

**Comment by dhansen601** [comment]
+1

Even if discussion on here doesn't lead anywhere, we could at very least start planning a community round table at the Dev Summit to get interested parties together for a more unified voice. There could be a lot of benifits to giving the community open access.

**Comment by stdavis** [comment]
At the very least running it through something like: [js-beautify](https://www.npmjs.com/package/js-beautify) would be helpful for debugging. [esrislurp](https://www.npmjs.com/package/esrislurp) does this and I've grown accustom to it.

**Comment by odoe** [comment]
Sorry folks, I forgot to disable issues for this repo.

It acts almost like a mirror of the CDN, as it still falls under the same guidelines. All issues still need to go through normal channels.

https://github.com/Esri/arcgis-js-api#issues

This repo is simply a source for the `bower` installs. 

Sorry about that.
